### ISSUE TITLE
ApplicationInsights: InstrumentationKey based APIs are marked Obsolete

### ISSUE THREAD

**Issue by DuncanP62** [jdvor/appmetrics-applicationinsights#10]
Hi Jan
Don't know if you're aware but Microsoft have announced that support for instrumentation key–based global ingestion in Application Insights will end on 25/3/2025 (see https://azure.microsoft.com/en-gb/updates/technical-support-for-instrumentation-key-based-global-ingestion-in-application-insights-will-end-on-31-march-2025/). The current version of the ApplicationInsights SDK has also deprecated the constructors that accept an instrumentation key and marked them as Obsolete, so your library no longer compiles with that version. The recommended approach is to "Use the default constructor and set the ConnectionString property instead" (see https://github.com/microsoft/ApplicationInsights-dotnet/issues/2560).
Duncan

**Comment by jdvor** [comment]
yes, v3.0.0 accepts only full connection string and not instrumentation key alone
