### ISSUE TITLE
ResetOnReporting on Counters appears not to be obeyed

### ISSUE THREAD

**Issue by DuncanP62** [jdvor/appmetrics-applicationinsights#2]
Hi jdvor. First thanks for putting in the effort to create this reporter.
I've been trialling App.Metrics with the ApplicationInsights reporter over the last few days and have noticed that although I set ResetOnReporting to true when creating a CounterOptions, the counts appearing in the App Insights custom metric are not in fact being reset after each report. In an attempt to identify where I'd gone wrong I fired up your sandbox console app but with one small change:

        public static CounterOptions CounterOne => new CounterOptions
        {
            Name = "counter_one",
            **ResetOnReporting = true**
        };

and found that the counts reported for counter_one were also not being reset (i.e. growing by 30 each report, with default settings of recordEvery = 2 secs and reportEvery = 60 secs).

I have no idea whether this is still some mistake I'm making, a possible issue with the ApplicationInsights reporter or with App.Metrics itself, but I'd be grateful for any assistance.
Thanks

Update: I've now found that this issue can be resolved with an additional extension method (in Extensions.cs):

        internal static void CopyTo(this CounterValueSource source, MetricTelemetry mt)
        {
            mt.Sum = source.ValueProvider.GetValue(source.ResetOnReporting).Count;
        }

and a change to the Translate method for CounterValueSource (in ApplicationInsightsReporter.cs):

            source.Value.CopyTo(mt);
replaced with
            source.CopyTo(mt);

Cheers

**Comment by jdvor** [comment]
I'll check that out.

**Comment by jdvor** [comment]
Confirmed and fixed by using your solution. Version 1.0.1 (nuget.org).
