### ISSUE TITLE
Nuget package targeting AMD64

### ISSUE THREAD

**Issue by wokket** [jdvor/appmetrics-applicationinsights#3]
G'day mate,

When I install the package via nuget I get the following build warning:

`There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "{{Local file path}}\.nuget\packages\app.metrics.reporting.applicationinsights\1.0.1\lib\netstandard2.0\App.Metrics.Reporting.ApplicationInsights.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.`

My .Net Core applications are all targeting `Any CPU` as a build target.

**Comment by jdvor** [comment]
The library targets 64bit (x64 platform).

```
D:\workspace\app.metrics.reporting.applicationinsights.1.0.1\lib\netstandard2.0>corflags App.Metrics.Reporting.ApplicationInsights.dll
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.8.3928.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32+
CorFlags  : 0x1
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 0
```

You are most likely building 32bit app/lib and therefore getting the warning. 
I'll review if the x64 targeting is necessary for the library itself (probably isn't).

**Comment by DuncanP62** [comment]
Hi Jan
Just wondering whether there's any update on this one? The other App.Metrics libraries all seem to be built targeting "Any CPU", so it would make sense for yours to do the same. I can create a local version for my own use but it would be great to have the official version updated.
Thanks
Duncan

**Comment by Teletraan1** [comment]
Also interesting in the status of this. I was just about to include this package, but I curious how it would affect our Docker containers using the standard MS images.

**Comment by jdvor** [comment]
[1.0.2](https://www.nuget.org/packages/App.Metrics.Reporting.ApplicationInsights/) targets AnyCPU
