### ISSUE TITLE
Does not support App.Metrics.Core 4.0.0 or higher

### ISSUE THREAD

**Issue by scrivuk** [jdvor/appmetrics-applicationinsights#5]
Hi, 

looking forward to using your very useful project. However, in my current situation I need to pair this with the NServiceBus reporting package which is set at App.Metrics.Core 4.1.0. 

Is there any plan to move this project on to the newer versions of App.Metrics.*?

Thanks in advance,
James.

**Comment by jdvor** [comment]
Yes, I will support new version of App.Metrics soon. However since it's major version upgrade (3 -> 4, thus announcing breaking changes) I need to find the time to review those.

**Comment by jdvor** [comment]
I've released version 1.0.3 which is tested with AppMetrics 4.1.0.
