### ISSUE TITLE
Extended Socket Exception directly after sending the report

### ISSUE THREAD

**Issue by benzmarkus** [jdvor/appmetrics-applicationinsights#9]
Hi,

using AppMetrics 4.3 and the Insight reporter in version 2.1.0. Currently the report is not reporting. I wrote a test nodejs script and successfully sent a metric to Insight with the same ApplicationInsightsInstrumentationKey and it worked but with C# I get exceptions. With the node script I find the metric in Insights and with C# I don't.

Net5 is currently used with App.Metrics 4.3.0 and App.Metrics.Reporting.ApplicationInsights 2.1.0.

*********************
Output:
*********************
Application Insights Telemetry: {"name":"AppMetrics","time":"2021-12-13T13:52:12.1717697Z","iKey":"<key>","tags":{"ai.cloud.roleInstance":"testns.local","ai.internal.sdkVersion":"dotnetc:2.16.0-18277"},"data":{"baseType":"MetricData","baseData":{"ver":2,"metrics":[{"ns":"TestNS","name":"TestNsService.rate","kind":"Aggregation","value":0.8744301895903686,"count":1}],"properties":{"Version":"1.0.0.0","context":"Service","appMetricsType":"meter","unit":"s"}}}}
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.NameResolution.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll

**Comment by jdvor** [comment]
I could not replicate the issue you are describing. 2.1. seems to me working fine. If you'd provide me a repo with minimal project to demonstrate the issue I'd look into it; otherwise I would close the issue in few weeks.
Also, I would release 2.2 version soon with updated dependencies and few changes around code analysis, so you could give it a shot.
